name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-workflow.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-workflow.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Run Tests
        run: |
          cd backend
          mvn test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: backend/**/target/surefire-reports/

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-jars
          path: backend/**/target/*.jar

  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd backend
          mvn sonar:sonar -Dsonar.projectKey=paynext-backend -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test, code-quality]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download JAR artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-jars
          path: backend

      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "ENV_TAG=latest" >> $GITHUB_ENV
          else
            echo "ENV_TAG=develop" >> $GITHUB_ENV
          fi

      - name: Build and push Eureka Server
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          build-args: |
            SERVICE_NAME=eureka-server
          push: true
          tags: abrar2030/paynext-eureka-server:${{ env.ENV_TAG }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          build-args: |
            SERVICE_NAME=api-gateway
          push: true
          tags: abrar2030/paynext-api-gateway:${{ env.ENV_TAG }}

      - name: Build and push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          build-args: |
            SERVICE_NAME=user-service
          push: true
          tags: abrar2030/paynext-user-service:${{ env.ENV_TAG }}

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          build-args: |
            SERVICE_NAME=payment-service
          push: true
          tags: abrar2030/paynext-payment-service:${{ env.ENV_TAG }}

      - name: Build and push Notification Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          build-args: |
            SERVICE_NAME=notification-service
          push: true
          tags: abrar2030/paynext-notification-service:${{ env.ENV_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/eureka-server-deployment.yaml
          kubectl apply -f kubernetes/api-gateway-deployment.yaml
          kubectl apply -f kubernetes/user-service-deployment.yaml
          kubectl apply -f kubernetes/payment-service-deployment.yaml
          kubectl apply -f kubernetes/notification-service-deployment.yaml

      - name: Verify deployments
        run: |
          kubectl rollout status deployment/eureka-server
          kubectl rollout status deployment/api-gateway
          kubectl rollout status deployment/user-service
          kubectl rollout status deployment/payment-service
          kubectl rollout status deployment/notification-service
