---
- name: Deploy User Service
  hosts: user_service
  become: true
  roles:
    - role: user-service
  vars:
    eureka_server_url: "http://eureka-server:8001/eureka"
    jwt_secret: "your_jwt_secret_here"
