---
- name: Deploy Payment Service
  hosts: payment_service
  become: true
  roles:
    - role: payment-service
  vars:
    eureka_server_url: "http://eureka-server:8001/eureka"
    jwt_secret: "your_jwt_secret_here"
