CREATE TABLE CUSTOMERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    country_region VARCHAR(55) NOT NULL,
    street_and_house_number VARCHAR(100) NOT NULL,
    city VARCHAR(60) NOT NULL,
    postal_code VARCHAR(18) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    email VARCHAR(254) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PAYMENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    amount DECIMAL(19,2) NOT NULL,
    payer_name VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(50) NOT NULL UNIQUE,
    payment_method VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ORDERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE NOT NULL,
    customer_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(id),
    FOREIGN KEY (payment_id) REFERENCES PAYMENTS(id)
);

CREATE TABLE USERS (
    username VARCHAR(255) PRIMARY KEY NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL
);

CREATE TABLE AUTHORITIES (
    username VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username)
);
