CREATE TABLE TRANSACTIONS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id VARCHAR(255) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    transaction_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CUSTOMERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city VARCHAR(60) NOT NULL,
    country_region VARCHAR(55) NOT NULL,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    postal_code VARCHAR(18) NOT NULL,
    street_and_house_number VARCHAR(100) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ORDERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE NOT NULL,
    transaction_id BIGINT,  -- Foreign key to the TRANSACTIONS table
    customer_id BIGINT,     -- Foreign key to the CUSTOMERS table
    PRIMARY KEY (id)
);

CREATE TABLE USERS (
    username VARCHAR(255) PRIMARY KEY NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL
);

CREATE TABLE AUTHORITIES (
    username VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username)
);
