apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paynext-admin-binding
  namespace: paynext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paynext-admin
subjects:
  - kind: ServiceAccount
    name: paynext-admin-sa
    namespace: paynext
