apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paynext-viewer-binding
  namespace: paynext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paynext-viewer
subjects:
  - kind: ServiceAccount
    name: paynext-viewer-sa
    namespace: paynext
