apiVersion: v1
kind: Service
metadata:
  name: paynext-prometheus
  namespace: paynext
  labels:
    app.kubernetes.io/name: paynext
    app.kubernetes.io/instance: paynext
    app.kubernetes.io/managed-by: Helm
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
