apiVersion: v1
kind: ConfigMap
metadata:
  name: paynext-prometheus-config
  namespace: paynext
  labels:
    app.kubernetes.io/name: paynext
    app.kubernetes.io/instance: paynext
    app.kubernetes.io/managed-by: Helm
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.rules
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8002']
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8003']
      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:8004']
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8005']
