---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: abrar2030/backend-notification-service:latest
          ports:
            - containerPort: 8005
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8001/eureka"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paynext-secrets
                  key: jwt_secret
