apiVersion: v1
kind: Secret
metadata:
  name: paynext-secrets
  namespace: paynext
  labels:
    app.kubernetes.io/name: paynext
    app.kubernetes.io/instance: paynext
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  jwt_secret: UkVQTEFDRV9XSVRIX1NFQ1VSRV9KV1RfU0VDUkVU
  payment_gateway_api_key: UkVQTEFDRV9XSVRIX1BBWU1FTlRfR0FURVdBWV9BUElfS0VZ
  email_service_api_key: UkVQTEFDRV9XSVRIX0VNQUlMX1NFUlZJQ0VfQVBJX0tFWQ==
  sms_service_api_key: UkVQTEFDRV9XSVRIX1NNU19TRVJWSUNFX0FQSV9LRVk=
