---
apiVersion: v1
kind: Service
metadata:
  name: fintech-payment-frontend
  labels:
    app: fintech-payment-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: fintech-payment-frontend
