apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paynext-backup-pvc
  namespace: paynext
  labels:
    app.kubernetes.io/name: paynext
    app.kubernetes.io/instance: paynext
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
