---

global:
  namespace: paynext
  ingressClass: nginx
eurekaServer:
  image:
    repository: abrar2030/paynext/eureka-server
    tag: latest
  service:
    port: 8001
    type: ClusterIP
apiGateway:
  image:
    repository: abrar2030/paynext/api-gateway
    tag: latest
  service:
    port: 8002
    type: ClusterIP
  env:
    JWT_SECRET: your_jwt_secret_here
userService:
  image:
    repository: abrar2030/paynext/user-service
    tag: latest
  service:
    port: 8003
    type: ClusterIP
  env:
    EUREKA_SERVER_URL: http://eureka-server:8001/eureka/
paymentService:
  image:
    repository: abrar2030/paynext/payment-service
    tag: latest
  service:
    port: 8004
    type: ClusterIP
  env:
    EUREKA_SERVER_URL: http://eureka-server:8001/eureka/
    JWT_SECRET: your_jwt_secret_here
notificationService:
  image:
    repository: abrar2030/paynext/notification-service
    tag: latest
  service:
    port: 8005
    type: ClusterIP
  env:
    EUREKA_SERVER_URL: http://eureka-server:8001/eureka/
    JWT_SECRET: your_jwt_secret_here
fintechPaymentFrontend:
  image:
    repository: abrar2030/paynext/fintech-payment-frontend
    tag: latest
  service:
    port: 80
    type: ClusterIP
  env:
    REACT_APP_API_BASE_URL: http://api-gateway:8080
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: frontend.paynext.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend
          port: 80
    - host: fintech-payment.paynext.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: fintech-payment-frontend
          port: 80
  tls:
    - secretName: paynext-tls
      hosts:
        - frontend.paynext.local
        - fintech-payment.paynext.local
imagePullSecrets:
  - name: regcred
