---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: abrar2030/backend:payment-service
          ports:
            - containerPort: 8004
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8001/eureka"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paynext-secrets
                  key: jwt_secret
