---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: NodePort
  ports:
    - port: 8004
      targetPort: 8004
      nodePort: 32002
  selector:
    app: payment-service
