---
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker and Build Images
        run: |
          cd backend
          for service in eureka-server api-gateway user-service payment-service notification-service; do
            docker buildx build -t abrar2030/paynext-$service -f ../Dockerfile --build-arg SERVICE_NAME=$service .
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push abrar2030/paynext-$service
          done
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f kubernetes/eureka-server-deployment.yaml
          kubectl apply -f kubernetes/api-gateway-deployment.yaml
          kubectl apply -f kubernetes/user-service-deployment.yaml
          kubectl apply -f kubernetes/payment-service-deployment.yaml
          kubectl apply -f kubernetes/notification-service-deployment.yaml
