apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          ports:
            - containerPort: 8003
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8001/eureka"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paynext-secrets
                  key: jwt_secret
