apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paynext-chart.name" . }}-notification-service
  labels:
    app: {{ include "paynext-chart.name" . }}-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paynext-chart.name" . }}-notification-service
  template:
    metadata:
      labels:
        app: {{ include "paynext-chart.name" . }}-notification-service
    spec:
      containers:
          - name: notification-service
            image: "{{ .Values.notificationService.image.repository }}:{{ .Values.notificationService.image.tag }}"
            ports:
              - containerPort: {{ .Values.notificationService.service.port }}
            env:
              - name: EUREKA_SERVER_URL
                value: "{{ .Values.notificationService.env.EUREKA_SERVER_URL }}"
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: paynext-secrets
                    key: jwt_secret
