---

- name: Restart user-service
  service:
    name: user-service
    state: restarted
- name: Notify dependent services of user-service restart
  debug:
    msg: "User service has been restarted. Notifying dependent services..."
- name: Wait for user-service to be available
  uri:
    url: "http://{{ inventory_hostname }}:8003/health"
    status_code: 200
    method: GET
    retries: 5
    delay: 10
  register: user_service_health
  until: user_service_health.status == 200
