---

- name: Copy Payment Service application jar
  copy:
    src: /path/to/payment-service.jar
    dest: /opt/payment-service/payment-service.jar
    owner: root
    group: root
    mode: '0755'
- name: Install dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - java-11-openjdk
    - unzip
- name: Configure Payment Service environment variables
  template:
    src: payment-service.env.j2
    dest: /etc/payment-service.env
    mode: '0644'
- name: Create Payment Service systemd service file
  template:
    src: payment-service.service.j2
    dest: /etc/systemd/system/payment-service.service
  notify:
    - Reload systemd
    - Restart Payment Service
