---

name: Backend CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [eureka-server, api-gateway, user-service, payment-service, notification-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Build and Test ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: |
          mvn clean install -DskipTests=false
      - name: Archive Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.service }}-test-results
          path: backend/${{ matrix.service }}/target/surefire-reports
